apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-app-of-apps
  namespace: argocd
  labels:
    app: myapp
    type: app-of-apps
spec:
  project: default

  source:
    repoURL: https://github.com/juandavimedina/test-app-k8.git
    targetRevision: develop
    path: argocd

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

    automated:
      selfHeal: false
      prune: true
  revisionHistoryLimit: 10
