apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-app-of-apps
  namespace: argocd
  labels:
    app: myapp
    type: app-of-apps
spec:
  project: default

  source:
    repoURL: https://github.com/juandavimedina/test-app-k8.git
    targetRevision: develop
    path: argocd

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

    automated:
      selfHeal: true
      prune: true
      allowEmpty: false

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10
