apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-staging
  namespace: argocd
  labels:
    environment: staging
    app: myapp
spec:
  project: default

  source:
    repoURL: https://github.com/juandavimedina/test-app-k8.git
    targetRevision: main
    path: myapp
    helm:
      valueFiles:
        - values-staging.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: myapp-staging

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

    automated:
      selfHeal: true
      prune: true
      allowEmpty: false

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10
